stages:
  - build
  - upload

# Start by using a pipeline that uses the `helm packages` command to package
# up the laravel-staging chart. Only trigger if the tag contains "laravel-staging"
build laravel staging chart:
  stage: build
  image: 
    name: alpine/helm:3.5.4
    entrypoint: [""]
  variables:
    # Need to trim out the 'laravel-staging-' prefix from the tag name
    CHART_VERSION: ${CI_COMMIT_TAG#laravel-staging-}
  script:
    - cd charts
    - helm package laravel-staging --version $CHART_VERSION
  rules:
    # Check if tag contains "laravel-staging"
    - if: $CI_COMMIT_TAG =~ /^laravel-staging-.*/
  artifacts:
    paths:
      - "**/*.tgz"
    expire_in: "1 week"


upload laravel staging chart:
  stage: upload
  image: curlimages/curl:latest
  variables:
    GIT_STRATEGY: none
    # Need to trim out the 'laravel-staging-' prefix from the tag name
    CHART_VERSION: ${CI_COMMIT_TAG#laravel-staging-}
  dependencies:
    - build laravel staging chart
  rules:
    # Check if tag contains "laravel-staging"
    - if: $CI_COMMIT_TAG =~ /^laravel-staging-.*/
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@charts/laravel-staging-$CI_COMMIT_TAG.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'