stages:
  - build
  - upload

# Start by using a pipeline that uses the `helm packages` command to package
# up the laravel-staging chart.
build-laravel-staging:
  stage: build
  image: alpine/helm:3.5.4
  script:
    - helm package laravel-staging --version $CI_COMMIT_TAG
  only:
    - tags
  artifacts:
    paths:
      - laravel-staging-*.tgz


upload-laravel-staging:
  stage: upload
  image: curlimages/curl:latest
  only:
    - tags
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@laravel-staging-$CI_COMMIT_TAG.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'