stages:
  - build
  - upload

# Start by using a pipeline that uses the `helm packages` command to package
# up the laravel-staging chart.
build charts:
  stage: build
  image: 
    name: alpine/helm:3.5.4
    entrypoint: [""]
  script:
    - cd charts
    - helm package laravel-staging --version $CI_COMMIT_TAG
    - helm package drupal-staging --version $CI_COMMIT_TAG
  only:
    - tags
  artifacts:
    paths:
      - "**/*.tgz"


upload charts:
  stage: upload
  image: curlimages/curl:latest
  dependencies:
    - build charts
  only:
    - tags
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@charts/laravel-staging-$CI_COMMIT_TAG.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@charts/drupal-staging-$CI_COMMIT_TAG.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'