include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    directives_ordering: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
