name: koality_tools
description: A collection of useful scripts for various projects.
version: 0.6.3
repository: https://gitlab.codekoalas.com/tools/koality_tools

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.0
  cli_completion: ^0.3.0
  dcli: ^2.3.0
  dio: ^5.0.0
  equatable: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mason_logger: ^0.2.0
  path: ^1.8.0
  pub_updater: ^0.3.0
  riverpod: ^2.3.0
  riverpod_annotation: ^2.1.0
  sprintf: ^7.0.0
  very_good_analysis: ^5.0.0+1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.2.1
  riverpod_lint: ^2.0.4
  test: ^1.19.2

executables:
  koality:
