apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  annotations:
    {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
    {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    layer: laravel
{{ include "sharedlabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      layer: laravel
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
        {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
        {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
      labels:
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        layer: laravel
{{ include "sharedlabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "serviceAccountName" . }}
      # This will wait for MySQL to be ready and then check if the DB_NAME database exists and if it doesn't it will create it.
{{- if not .Values.persistence.ephemeral.enabled }}
      initContainers:
      # Check for if the DB_DATABASE database exists and if it doesn't, we create it.
      - name: create-db
        image: {{ .Values.deployment.initContainerImage }}
        imagePullPolicy: "Always"
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
        env:
        - name: DB_DATABASE
          value: {{ .Values.persistence.databaseName }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-host"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-port"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-user"
        - name: MYSQL_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ck-database-instance-password
              key: MYSQL_MASTER_PASSWORD
        - name: DB_USERNAME
          value: {{ .Values.persistence.databaseUser }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
{{- end }}
      # The deployment container spec
      containers:
      # Main container deployment
      - name: {{ .Values.deployment.name }}
        image: {{ template "imagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.persistence.limits.cpu }}
            memory: {{ .Values.persistence.limits.memory }}
          requests:
            cpu: {{ .Values.persistence.requests.cpu }}
            memory: {{ .Values.persistence.requests.memory }}
        ports:
        - name: http
          containerPort: 80
{{- if .Values.persistence.enabled }}
        volumeMounts:
{{- range $volume := .Values.persistence.volumes }}
          - name: {{ $volume.name | quote }}
            mountPath: {{ $volume.mount.mountPath | quote }}
            {{- if $volume.mount.subPath }}
            subPath: {{ $volume.mount.subPath | quote }}
            {{- end }}
{{- end }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
        {{- if and .Values.application.secretName }}
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        - secretRef:
            name: {{ template "appname" . }}-secrets
        env:
{{- if .Values.persistence.ephemeral.enabled }}
        # If using ephemeral database have it point to the ephemeral db service and host
        - name: DB_DATABASE
          value: {{ .Values.gitlab.env }}
        - name: DB_HOST
          value: {{ template "appname" . }}-database
{{- else }}
        - name: DB_DATABASE
          value: {{ .Values.persistence.databaseName }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-host"
{{- end }}
        - name: DB_USERNAME
          value: {{ .Values.persistence.databaseUser }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-port"
{{- if and (.Values.aws.s3.enabled) (.Values.aws.s3.createNew) }}
        - name: AWS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "appname" . }}-s3-config
              key: "gitlab-managed-apps.{{ template "appname" . }}-s3-location"
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: {{ template "appname" . }}-s3-config
              key: "gitlab-managed-apps.{{ template "appname" . }}-s3-bucket-name"
{{- end }}
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: APP_KEY
{{- if .Values.echo.enabled }}
      - name: {{ .Values.deployment.name }}-echo
        image: {{ .Values.echo.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.echo.limits.cpu }}
            memory: {{ .Values.echo.limits.memory }}
          requests:
            cpu: {{ .Values.echo.requests.cpu }}
            memory: {{ .Values.echo.requests.memory }}
        ports:
        - containerPort: {{ .Values.echo.port }}
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
        {{- if .Values.application.secretName }}
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        - secretRef:
            name: {{ template "appname" . }}-secrets
        # If we have deployment.configMaps set then we need to create a volume mount for each one.
        volumeMounts:
        {{- if .Values.deployment.configMaps }}
        {{- range $key, $value := .Values.deployment.configMaps }}
        # Now we need to map each one to the container using the mountPath as the mount
        # and then each key as the name.
          - name: {{ $key }}
            mountPath: {{ $value.mountPath }}
        {{- end }}
        {{- end }}
        {{- if .Values.echo.config }}
          - name: echo-server-file
            mountPath: {{ default "/var/www/html" .Values.echo.config.mountPath }}
        {{- end }}
{{- end }}

      imagePullSecrets:
      - name: regcred
{{- if .Values.persistence.enabled }}
{{- $context := . }}
      volumes:
{{- if .Values.echo.config }}
        - name: echo-server-file
          configMap:
            name: {{ template "appname" . }}-echo-server-file
{{- end }}
# Check for deployment.configMaps and then map each of them to a volume.
{{- if .Values.deployment.configMaps }}
{{- range $key, $value := .Values.deployment.configMaps }}
        - name: {{ $key }}
          configMap:
            name: {{ template "appname" . }}-{{ $key }}
{{- end }}
{{- end }}
{{- range $volume := .Values.persistence.volumes }}
        - name: {{ $volume.name | quote }}
          persistentVolumeClaim:
            {{ $args := dict "context" $context "name" $volume.name }}
            claimName: {{ template "pvcName" $args }}
{{- end }}
{{- end }}
