{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "appname" . }}-redis
  labels:
    app: {{ template "appname" . }}
    track: "{{ $.Values.application.track }}"
    tier: "{{ $.Values.application.tier }}"
    layer: redis
spec:
  ports:
  - port: {{ .Values.redis.port }}
    protocol: TCP
  selector:
    app: {{ template "appname" . }}
    track: "{{ $.Values.application.track }}"
    tier: "{{ $.Values.application.tier }}"
    layer: redis
  type: ClusterIP
{{- end -}}