{{- if and .Values.aws.s3.enabled .Values.aws.s3.createNew -}}
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: {{ .Values.aws.s3.bucket }}
spec:
  name: {{ .Values.aws.s3.bucket }}
{{- if .Values.aws.s3.tagSets }}
  tagging:
    tagSet:
{{- range $tag := .Values.aws.s3.tagSets }}
    - key: "{{ $tag.key }}"
      value: "{{ $tag.value }}"
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appname" . }}-s3-config
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: {{ template "appname" . }}-s3-location
spec:  
  to:
    name: {{ template "appname" . }}-s3-config # Matches the ConfigMap we created above
    kind: configmap
    namespace: gitlab-managed-apps
  from:
    path: ".status.location"
    resource:
      group: s3.services.k8s.aws
      kind: Bucket
      name: {{ .Values.aws.s3.bucket }}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: {{ template "appname" . }}-s3-bucket-name
spec:  
  to:
    name: {{ template "appname" . }}-s3-config # Matches the ConfigMap we created above
    kind: configmap
    namespace: gitlab-managed-apps
  from:
    path: ".name"
    resource:
      group: s3.services.k8s.aws
      kind: Bucket
      name: {{ .Values.aws.s3.bucket }}
{{- end -}}
