{{- if and .Values.aws.s3.enabled .Values.aws.s3.createNew }}
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: {{ template "appname" . }}-s3-location
  labels:
    app: {{ template "appname" . }}
spec:  
  to:
    name: {{ template "appname" . }} # Matches the ConfigMap we created above
    kind: configmap
    namespace: gitlab-managed-apps
  from:
    path: ".status.location"
    resource:
      group: s3.services.k8s.aws
      kind: Bucket
      name: {{ .Values.aws.s3.bucket }}