apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
data:
  LETSENCRYPT_HOST: {{ .Values.deployment.letsEncryptHost }}
  APP_NAME: {{ template "appname" . }}
  APP_ENV: {{ .Values.deployment.appEnv }}
  APP_URL: {{ .Values.deployment.virtualHost }}
  # @TODO:  needs to become a secret
  # APP_KEY=base64:D5V/DRUQq+oftU66FWmBz4Y1z/LYNxPohCXxTwEg/+g=
  APP_DEBUG: false
  APP_URL: {{ .Values.deployment.appUrl }}
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  # Should come from the Field Exports from the RDS controller.
  # DB_HOST: {{ .Values.persistence.databaseHost }}
  # DB_PORT: {{ .Values.persistence.databasePort }}
  DB_DATABASE: {{ .Values.persistence.databaseName }}
  DB_USERNAME: {{ .Values.persistence.databaseUser }}
  # @TODO: Create secret
  # DB_PASSWORD: {{ .Values.persistence.databasePassword }}
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DRIVER: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120
  MEMCACHED_HOST: memcached
  REDIS_HOST: {{ template "appname" . }}-redis
  REDIS_PASSWORD: {{ .Values.redis.password }}
  REDIS_PORT: {{ .Values.redis.port }}
  MAIL_MAILER: {{ .Values.mail.mailer }}
  MAIL_HOST: {{ .Values.mail.host }}
  MAIL_PORT: {{ .Values.mail.port }}
  MAIL_USERNAME: {{ .Values.mail.username }}
  MAIL_PASSWORD: {{ .Values.mail.password }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption }}
  MAIL_FROM_ADDRESS: {{ .Values.mail.from.address }}
  MAIL_FROM_NAME: {{ .Values.mail.from.name }}
  # @TODO: Probably a secret or from the S3 controller
  # AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
  # @TODO: Make a secret; or probably handled by the ACK S3 controller
  # AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  # @TODO: have it select the S3 controller if it exists
  # AWS_DEFAULT_REGION: {{ .Values.aws.region }}
  # AWS_BUCKET: {{ .Values.aws.s3.bucket }}
  # AWS_USE_PATH_STYLE_ENDPOINT: {{ .Values.aws.s3.usePathStyleEndpoint }}
  PUSHER_APP_ID: {{ .Values.pusher.appId }}
  PUSHER_APP_KEY: {{ .Values.pusher.appKey }}
  PUSHER_APP_SECRET: {{ .Values.pusher.appSecret }}
  PUSHER_APP_CLUSTER: {{ .Values.pusher.appCluster }}
  MIX_PUSHER_APP_KEY: {{ .Values.mixpusher.appKey }}
  MIX_PUSHER_APP_CLUSTER: {{ .Values.mixpusher.appCluster}}
