apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
data:
  VIRTUAL_HOST: "{{ .Values.deployment.virtualHost }}"
  DRUPAL_TRUSTED_HOSTS: "{{ .Values.deployment.virtualHost }}"
  LETSENCRYPT_HOST: "{{ .Values.deployment.letsEncryptHost }}"
  DRUPAL_BASE_URL: "{{ .Values.deployment.drupalBaseUrl }}"
  APACHE_DOCROOT: "{{ .Values.deployment.apacheDocroot }}"
  DB_DATABASE: "{{ .Values.persistence.databaseName }}"
  DB_USERNAME: "{{ .Values.persistence.databaseUser }}"
  SITE_ENV: "{{ .Values.deployment.siteEnv }}"
