apiVersion: {{ .Values | get "apiVersion" "apps/v1" }}
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
data:
  VIRTUAL_HOST: {{ .Values.deployment.virtualHost" }}
  LETSENCRYPT_HOST: {{ .Values.deployment.letsEncryptHost }}
  DRUPAL_BASE_URL: {{ .Values.deployment.drupalBaseUrl }}
  APACHE_DOCROOT: {{ .Values | get "deployment.apacheDocroot" "/var/www/html/docroot" }}
  DATABASE_NAME: {{ .Values.persistence.databaseName}}
  DATABASE_USERNAME: {{ .Values.persistence.databaseUser }}
  DATABASE_HOST: {{ .Values.persistence.databaseHost }}
  SITE_ENV: {{ .Values.deployment.siteEnv }}
