apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
data:
  VIRTUAL_HOST: {{ .Values.deployment.virtualHost }}
  LETSENCRYPT_HOST: {{ .Values.deployment.letsEncryptHost }}
  DRUPAL_BASE_URL: {{ .Values.deployment.drupalBaseUrl }}
  APACHE_DOCROOT: {{ .Values.deployment.apacheDocroot }}
  DATABASE_NAME: {{ .Values.persistence.databaseName}}
  DATABASE_USERNAME: {{ .Values.persistence.databaseUser }}
  DATABASE_HOST: {{ .Values.persistence.databaseHost }}
  SITE_ENV: {{ .Values.deployment.siteEnv }}
