{{- if .Values.persistence.ephemeral.enabled -}}
apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}-database
  labels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      layer: database
spec:
  replicas: {{ .Values.cron.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      layer: database
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        layer: database
    spec:
      containers:
      - name: {{ template "appname" . }}-database
        image: {{ .Values.persistence.ephemeral.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
{{- if .Values.application.secretName }}
        - secretRef:
            name: {{ .Values.application.secretName }}
{{- end }}
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.gitlab.env }}
        - name: MYSQL_USER
          value: {{ .Values.persistence.databaseUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
        - name: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-user"
        - name: MYSQL_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ck-database-instance-password
              key: MYSQL_MASTER_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ck-database-instance-password
              key: MYSQL_MASTER_PASSWORD
        - name: DB_USERNAME
          value: {{ .Values.persistence.databaseUser }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
        - name: DB_DATABASE
          value: {{ .Values.persistence.databaseName }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-host"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-port"
      imagePullSecrets:
        - name: regcred
{{- end -}}
