apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  annotations:
    {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
    {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    layer: drupal
{{ include "sharedlabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      layer: drupal
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
        {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
        {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
      labels:
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        layer: drupal
{{ include "sharedlabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "serviceAccountName" . }}
      # This will wait for MySQL to be ready and then check if the DB_NAME database exists and if it doesn't it will create it.
{{- if not .Values.persistence.ephemeral.enabled }}
      initContainers:
      # Check for if the DB_DATABASE database exists and if it doesn't, we create it.
      - name: create-db
        image: {{ template "docker.image" (dict "Values" .Values.deployment.initContainerImage) }}
        imagePullPolicy: "Always"
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
        env:
        - name: DB_DATABASE
          value: {{ .Values.persistence.databaseName }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-host"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-port"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-user"
        - name: MYSQL_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ck-database-instance-password
              key: MYSQL_MASTER_PASSWORD
        - name: DB_USERNAME
          value: {{ .Values.persistence.databaseUser }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
{{- end }}
      # The deployment container spec
      containers:
      # Main container deployment.
      - name: {{ .Values.deployment.name }}
        image: {{ template "imagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.persistence.limits.cpu }}
            memory: {{ .Values.persistence.limits.memory }}
          requests:
            cpu: {{ .Values.persistence.requests.cpu }}
            memory: {{ .Values.persistence.requests.memory }}
        ports:
        - name: http
          containerPort: 80
{{- if .Values.persistence.enabled }}
        volumeMounts:
{{- range $volume := .Values.persistence.volumes }}
          - name: {{ $volume.name | quote }}
            mountPath: {{ $volume.mount.mountPath | quote }}
            {{- if $volume.mount.subPath }}
            subPath: {{ $volume.mount.subPath | quote }}
            {{- end }}
{{- end }}
{{- if .Values.deployment.configMapFiles }}
{{- range $key, $value := .Values.deployment.configMapFiles }}
          # Now we need to map each one to the container using the mountPath as the mount
          # and then each key as the name.
          - name: {{ $key }}
            mountPath: {{ default "/var/www/html" $value.mountPath }}
{{- end }}
{{- end }}
# Now let's map all the files into the container, using the path
# to the file as the mountPath value.
{{- if .Files }}
{{- range $path, $bytes := .Files }}
{{- if not (hasSuffix $path ".yaml") }}
          {{ $args := dict "context" $context "name" (base $path) }}
          - name: {{ template "cleanName" $args }}
            mountPath: {{ default "/var/www/html" (dir $path) }}
{{- end }}
{{- end }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "appname" . }}
        {{- if and .Values.application.secretName }}
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        - secretRef:
            name: {{ template "appname" . }}-secrets
        env:
{{- if .Values.persistence.ephemeral.enabled }}
        # If using ephemeral database have it point to the ephemeral db service and host
        - name: MYSQL_DATABASE
          value: {{ .Values.gitlab.env }}
        - name: MYSQL_SERVER
          value: {{ template "appname" . }}-database
{{- else }}
        - name: MYSQL_DATABASE
          value: {{ .Values.persistence.databaseName }}
        - name: MYSQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-host"
{{- end }}
        - name: MYSQL_USER
          value: {{ .Values.persistence.databaseUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appname" . }}-secrets
              key: DB_PASSWORD
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-instance-config
              key: "gitlab-managed-apps.mysql-instance-config-port"
      imagePullSecrets:
        - name: regcred
{{- if .Values.persistence.enabled }}
{{- $context := . }}
      volumes:
# Check for deployment.configMaps and then map each of them to a volume.
{{- if .Values.deployment.configMapFiles }}
{{- range $key, $value := .Values.deployment.configMapFiles }}
        - name: {{ $key }}
          configMap:
            name: {{ template "appname" $context }}-{{ $key }}
{{- end }}
{{- end }}
# Now grab all included files and map them to config maps.
{{- if .Files }}
{{- range $path, $bytes := .Files }}
{{- if not (hasSuffix $path ".yaml") }}
        {{ $args := dict "context" $context "name" (base $path) }}
        - name: {{ template "cleanName" $args }}
          configMap:
            name: {{ template "cleanName" $args }}
{{- end }}
{{- end }}
{{- end }}
{{- range $volume := .Values.persistence.volumes }}
        - name: {{ $volume.name | quote }}
          persistentVolumeClaim:
            {{ $args := dict "context" $context "name" $volume.name }}
            claimName: {{ template "pvcName" $args }}
{{- end }}
{{- end }}

