apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlptRmlaV0Z1T21SSlJHbFRRV1l5SVhwSVluTm5iM2RXTVZvbE0xRXdlSFpYT1RWd1NRPT0iCgkJfSwKCQkicmVnaXN0cnkuY29kZWtvYWxhcy5jb20iOiB7CgkJCSJhdXRoIjogImFtOXphRHBGTTBwRVRtdDRhMFZoWTIxeVJGZDNPRzV2V2c9PSIKCQl9LAoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJhbTl6YUdaaFltVmhianBSVkhoR1RXUXRlbGh5UlRGRlozWkhSemhNYmc9PSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuMS1jZSAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson
