apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: "{{ .Values.dbcluster.name }}"
spec:
  allocatedStorage: 20
  dbInstanceClass: {{ .Values.dbcluster.instanceClass }}
  dbInstanceIdentifier: "{{ .Values.dbcluster.name }}"
  engine: mysql
  engineVersion: "{{ default "8.0" .Values.dbcluster.engineVersion }}"
  dbSubnetGroupName: {{ .Values.dbcluster.subnetGroupName }}
  multiAZ: {{ .Values.dbcluster.multiAZ }}
  masterUsername: "{{ .Values.dbcluster.username }}"
  masterUserPassword:
    namespace: {{ .Values.dbcluster.password.namespace }}
    name: "{{ .Values.dbcluster.password.secretKeyRef.name }}"
    key: {{ .Values.dbcluster.password.secretKeyRef.key }}
  performanceInsightsEnabled: false
{{- if .Values.dbcluster.vpcSecurityGroupIds }}
  vpcSecurityGroupIds:
{{- range $id := .Values.dbcluster.vpcSecurityGroupIds }}
    - {{ $id }}
{{- end }}
{{- end }}
